language: node_js
cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: 885222d2ddb26ef110f04edc9c079c87935142c9f99f286f147d9b0a4842fc5b
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
